openapi: 3.1.0
info:
  title: Budget Analyzer API
  description: API documentation for Budget Analyzer resources
  contact:
    name: Bleu Rubin
    email: support@bleurubin.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0"
externalDocs:
  description: Find more info here
  url: https://github.com/bleurubin/budget-analyzer-api
servers:
- url: http://localhost:8080/budget-analyzer-api
  description: Local environment
- url: https://api.bleurubin.com
  description: Production environment
tags:
- name: Transaction Handler
  description: Endpoints for operations on transactions
paths:
  /transactions/search:
    post:
      tags:
      - Transaction Handler
      summary: Search transactions
      description: Paginated search over transactions
      operationId: searchTransactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionFilter"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: internal_server_error
                title: Internal Server Error
                status: 500
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258834646Z
        "200":
          description: Search completed without errors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: service_unavailable
                title: Service Unavailable
                status: 503
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258852288Z
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: bad_request
                title: Bad Request
                status: 400
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258983419Z
  /transactions/import:
    post:
      tags:
      - Transaction Handler
      summary: Upload CSV file(s) containing transactions
      description: Imports transactions from one or more CSV files for a given account
        and format.
      operationId: importTransactions
      parameters:
      - name: format
        in: query
        description: CSV format type
        required: true
        schema:
          type: string
        example: capital-one
      - name: accountId
        in: query
        description: Account ID to associate transactions with
        required: false
        schema:
          type: string
        example: checking-12345
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  description: CSV file(s) to upload
                  items:
                    type: string
                    format: binary
              required:
              - files
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: internal_server_error
                title: Internal Server Error
                status: 500
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258988466Z
        "200":
          description: Transactions imported successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "422":
          description: Request was correctly formatted but there were business rules
            violated by the request so it couldn't be processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: service_unavailable
                title: Service Unavailable
                status: 503
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258990174Z
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: bad_request
                title: Bad Request
                status: 400
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258991633Z
  /transactions:
    get:
      tags:
      - Transaction Handler
      summary: Get transactions
      description: Get all transactions
      operationId: getTransactions
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: internal_server_error
                title: Internal Server Error
                status: 500
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258993627Z
        "200":
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: service_unavailable
                title: Service Unavailable
                status: 503
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258994988Z
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: not_found
                title: Not Found
                status: 404
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258997648Z
  /transactions/{id}:
    get:
      tags:
      - Transaction Handler
      summary: Get transaction
      description: Get transaction by id
      operationId: getTransaction
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: internal_server_error
                title: Internal Server Error
                status: 500
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.258999660Z
        "200":
          description: Transaction found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: service_unavailable
                title: Service Unavailable
                status: 503
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.259001194Z
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: not_found
                title: Not Found
                status: 404
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.259002481Z
    delete:
      tags:
      - Transaction Handler
      summary: Delete transaction
      description: Delete transaction by id
      operationId: deleteTransaction
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: internal_server_error
                title: Internal Server Error
                status: 500
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.259003799Z
        "204":
          description: Transaction deleted successfully
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: service_unavailable
                title: Service Unavailable
                status: 503
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.259005Z
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
              example:
                type: not_found
                title: Not Found
                status: 404
                instance: /budget-analyzer-api/transactions
                timestamp: 2025-10-25T07:44:13.259006164Z
components:
  schemas:
    ApiErrorResponse:
      type: object
      description: Standard API error response format (RFC 7807-inspired)
      properties:
        type:
          type: string
          description: Machine-readable error type (slug or code)
          example: transaction_not_found
        title:
          type: string
          description: Short summary of the problem
          example: Transaction not found
        status:
          type: integer
          format: int32
          description: HTTP status code
          example: 404
        detail:
          type: string
          description: Detailed explanation of the problem
          example: Transaction with Id 123 could not be located.
        instance:
          type: string
          description: Request path or trace Id
          example: /transactions/123
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the error in ISO-8601 format
          example: 2023-10-15T14:30:00.500Z
        errors:
          type: array
          description: List of field-level validation errors (optional)
          items:
            $ref: "#/components/schemas/FieldError"
      required:
      - instance
      - status
      - timestamp
      - title
      - type
    FieldError:
      type: object
      description: Field-level validation error details
      properties:
        field:
          type: string
          description: Field that triggered the error
          example: email
        message:
          type: string
          description: Error message
          example: must be a valid email address
        rejectedValue:
          description: Value that caused the error
          example: invalid@email
      required:
      - field
      - message
      - rejectedValue
    TransactionFilter:
      type: object
      description: Filter for querying transactions by various fields
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the transaction
          example: 1
        accountId:
          type: string
          description: Identifier for the account associated with the transaction
          example: checking-3223
        bankName:
          type: string
          description: Name of the bank where the transaction occurred
          example: Capital One
        dateFrom:
          type: string
          format: date
          description: Start date for transaction date range
          example: 2025-10-01
        dateTo:
          type: string
          format: date
          description: End date for transaction date range
          example: 2025-10-14
        currencyIsoCode:
          type: string
          description: ISO currency code for the transaction
          example: USD
        minAmount:
          type: number
          description: Minimum transaction amount
          example: 10.0
        maxAmount:
          type: number
          description: Maximum transaction amount
          example: 500.0
        type:
          type: string
          description: Type of the transaction
          enum:
          - CREDIT
          - DEBIT
          example: DEBIT
        description:
          type: string
          description: Text to match in the transaction description
          example: Grocery
        createdAfter:
          type: string
          format: date-time
          description: Start of creation timestamp range
          example: 2025-10-14T00:00:00Z
        createdBefore:
          type: string
          format: date-time
          description: End of creation timestamp range
          example: 2025-10-15T00:00:00Z
        updatedAfter:
          type: string
          format: date-time
          description: Start of last update timestamp range
          example: 2025-10-14T00:00:00Z
        updatedBefore:
          type: string
          format: date-time
          description: End of last update timestamp range
          example: 2025-10-15T00:00:00Z
    Transaction:
      type: object
      description: Transaction entity representing a financial transaction
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the transaction
          example: 1
        accountId:
          type: string
          description: Identifier for the account associated with the transaction
          example: checking-3223
        bankName:
          type: string
          description: Name of the bank where the transaction occurred
          example: Capital One
        date:
          type: string
          format: date
          description: Date of the transaction
          example: 2025-10-14
        currencyIsoCode:
          type: string
          description: ISO currency code for the transaction
          example: USD
        amount:
          type: number
          description: Amount of the transaction
          example: 100.5
        type:
          type: string
          description: Type of the transaction
          enum:
          - CREDIT
          - DEBIT
          example: DEBIT
        description:
          type: string
          description: Description of the transaction
          example: Grocery shopping
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the transaction was created
          example: 2025-10-14T12:34:56Z
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the transaction was last updated
          example: 2025-10-14T12:34:56Z
        deleted:
          type: boolean
        deletedAt:
          type: string
          format: date-time
      required:
      - amount
      - bankName
      - createdAt
      - currencyIsoCode
      - date
      - description
      - id
      - type
      - updatedAt
